###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

enable_analytics: false

# Change the folder path name for your symlinked external content directory, empty if external symlinked directory is not used.
_symlinked_content_root_path: /Users/nob/Dropbox/statamic_contents/jointanet.com