###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

enable_analytics: false
